# Each service gets its own ServiceAccount — principle of least privilege.
# A compromised pod can only access what its ServiceAccount allows.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: ecommerce
  labels:
    app: frontend
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice-sa
  namespace: ecommerce
  labels:
    app: cartservice
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkoutservice-sa
  namespace: ecommerce
  labels:
    app: checkoutservice
automountServiceAccountToken: false
