apiVersion: v2
name: ecommerce
description: Online Boutique — Production-style Kubernetes learning project
type: application
version: 1.0.0
appVersion: "v0.10.5"
keywords:
  - ecommerce
  - microservices
  - kubernetes
  - online-boutique
maintainers:
  - name: neha.patil
    email: nehaspatil125000@gmail.com
