---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: ecommerce
  labels:
    app: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000

      containers:
        - name: shippingservice
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice:v0.10.5
          ports:
            - name: grpc
              containerPort: 50051
          envFrom:
            - configMapRef:
                name: shippingservice-config
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 10
            periodSeconds: 5

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]

      terminationGracePeriodSeconds: 30
